"""initial schema

Revision ID: 25356e6df5dd
Revises: 
Create Date: 2026-08-30 14:52:40.834895
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '25356e6df5dd'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kb_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('attrs', sa.JSON(), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kb_entries')),
    sa.UniqueConstraint('source_url', 'title', name='kb_source_title')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_tg_id'), ['tg_id'], unique=True)

    op.create_table('ai_query_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('escalated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ai_query_log_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_query_log'))
    )
    with op.batch_alter_table('ai_query_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_query_log_created_at'), ['created_at'], unique=False)

    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_log_actor_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_created_at'), ['created_at'], unique=False)

    op.create_table('document_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('doc_type', sa.String(length=64), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('requested_by', sa.Integer(), nullable=False),
    sa.Column('fulfilled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], name=op.f('fk_document_requests_requested_by_users')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_document_requests_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_requests'))
    )
    op.create_table('escalated_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('answered_by', sa.Integer(), nullable=True),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['answered_by'], ['users.id'], name=op.f('fk_escalated_questions_answered_by_users')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_escalated_questions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_escalated_questions'))
    )
    op.create_table('faq_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=400), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('keywords', sa.String(length=400), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_faq_entries_updated_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_faq_entries'))
    )
    op.create_table('reminders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=400), nullable=False),
    sa.Column('fire_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lead_minutes', sa.Integer(), nullable=False),
    sa.Column('repeat', sa.String(length=24), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_fired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_reminders_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reminders'))
    )
    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reminders_fire_at'), ['fire_at'], unique=False)

    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('short_name', sa.String(length=60), nullable=True),
    sa.Column('thread_id', sa.BigInteger(), nullable=True),
    sa.Column('teacher_kb_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['teacher_kb_id'], ['kb_entries.id'], name=op.f('fk_subjects_teacher_kb_id_kb_entries')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subjects')),
    sa.UniqueConstraint('name', name=op.f('uq_subjects_name'))
    )
    op.create_table('user_reminder_prefs',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lesson_lead_minutes', sa.Integer(), nullable=True),
    sa.Column('evening_digest_time', sa.Time(), nullable=True),
    sa.Column('dnd_start', sa.Time(), nullable=True),
    sa.Column('dnd_end', sa.Time(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_reminder_prefs_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_user_reminder_prefs'))
    )
    op.create_table('defense_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('on_date', sa.Date(), nullable=True),
    sa.Column('starts_at', sa.Time(), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('slots_open', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_defense_events_subject_id_subjects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_defense_events'))
    )
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('doc_type', sa.String(length=64), nullable=False),
    sa.Column('comment', sa.String(length=500), nullable=True),
    sa.Column('file_id', sa.String(length=300), nullable=False),
    sa.Column('file_unique_id', sa.String(length=120), nullable=True),
    sa.Column('mime', sa.String(length=120), nullable=True),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['document_requests.id'], name=op.f('fk_documents_request_id_document_requests')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_documents_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents'))
    )
    op.create_table('homework',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('text_norm', sa.Text(), nullable=False),
    sa.Column('ai_parsed', sa.JSON(), nullable=True),
    sa.Column('attachments', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('confirmations', sa.Integer(), nullable=False),
    sa.Column('confirmed_by', sa.JSON(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_homework_created_by_users')),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_homework_subject_id_subjects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_homework'))
    )
    with op.batch_alter_table('homework', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_homework_due_date'), ['due_date'], unique=False)

    op.create_table('lessons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('pair_no', sa.Integer(), nullable=False),
    sa.Column('starts_at', sa.Time(), nullable=False),
    sa.Column('ends_at', sa.Time(), nullable=True),
    sa.Column('week_parity', sa.String(length=8), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=True),
    sa.Column('room', sa.String(length=64), nullable=True),
    sa.Column('teacher', sa.String(length=200), nullable=True),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_lessons_subject_id_subjects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lessons'))
    )
    op.create_table('absence_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('on_date', sa.Date(), nullable=False),
    sa.Column('pair_no', sa.Integer(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=300), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('marked_by', sa.Integer(), nullable=True),
    sa.Column('is_excused', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_absence_records_document_id_documents')),
    sa.ForeignKeyConstraint(['marked_by'], ['users.id'], name=op.f('fk_absence_records_marked_by_users')),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_absence_records_subject_id_subjects')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_absence_records_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_absence_records'))
    )
    with op.batch_alter_table('absence_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_absence_records_on_date'), ['on_date'], unique=False)

    op.create_table('defense_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('at_time', sa.Time(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['defense_events.id'], name=op.f('fk_defense_slots_event_id_defense_events')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_defense_slots_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_defense_slots'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('defense_slots')
    with op.batch_alter_table('absence_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_absence_records_on_date'))

    op.drop_table('absence_records')
    op.drop_table('lessons')
    with op.batch_alter_table('homework', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_homework_due_date'))

    op.drop_table('homework')
    op.drop_table('documents')
    op.drop_table('defense_events')
    op.drop_table('user_reminder_prefs')
    op.drop_table('subjects')
    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reminders_fire_at'))

    op.drop_table('reminders')
    op.drop_table('faq_entries')
    op.drop_table('escalated_questions')
    op.drop_table('document_requests')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_created_at'))

    op.drop_table('audit_log')
    with op.batch_alter_table('ai_query_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_query_log_created_at'))

    op.drop_table('ai_query_log')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_tg_id'))

    op.drop_table('users')
    op.drop_table('kb_entries')
    # ### end Alembic commands ###
