"""roster entries, birthdays, holidays, media

Revision ID: a833b6d0f5af
Revises: 25356e6df5dd
Create Date: 2026-08-30 16:53:44.675790
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a833b6d0f5af'
down_revision: Union[str, Sequence[str], None] = '25356e6df5dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('holidays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_holidays_created_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_holidays'))
    )
    op.create_table('media_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('file_id', sa.String(length=300), nullable=False),
    sa.Column('added_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], name=op.f('fk_media_items_added_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media_items'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name_norm', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('birthday_day', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('birthday_month', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('birthday_year', sa.Integer(), nullable=True))
        batch_op.alter_column('tg_id',
               existing_type=sa.BIGINT(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_users_full_name_norm'), ['full_name_norm'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_full_name_norm'))
        batch_op.alter_column('tg_id',
               existing_type=sa.BIGINT(),
               nullable=False)
        batch_op.drop_column('birthday_year')
        batch_op.drop_column('birthday_month')
        batch_op.drop_column('birthday_day')
        batch_op.drop_column('full_name_norm')

    op.drop_table('media_items')
    op.drop_table('holidays')
    # ### end Alembic commands ###
