"""pinned tasks, topic lists, defense queues

Revision ID: a8c127853790
Revises: a833b6d0f5af
Create Date: 2026-08-30 18:37:06.514912
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a8c127853790'
down_revision: Union[str, Sequence[str], None] = 'a833b6d0f5af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pinned_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_pinned_tasks_created_by_users')),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_pinned_tasks_subject_id_subjects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pinned_tasks'))
    )
    op.create_table('topic_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_topic_lists_created_by_users')),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_topic_lists_subject_id_subjects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_topic_lists'))
    )
    op.create_table('topic_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('taken_by', sa.Integer(), nullable=True),
    sa.Column('taken_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['list_id'], ['topic_lists.id'], name=op.f('fk_topic_items_list_id_topic_lists')),
    sa.ForeignKeyConstraint(['taken_by'], ['users.id'], name=op.f('fk_topic_items_taken_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_topic_items'))
    )
    with op.batch_alter_table('defense_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('is_open', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_defense_events_created_by_users'), 'users', ['created_by'], ['id'])
        batch_op.drop_column('slots_open')
        batch_op.drop_column('on_date')
        batch_op.drop_column('starts_at')

    with op.batch_alter_table('defense_slots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('on_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('pair_no', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_reserve', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('booked_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('defense_slots', schema=None) as batch_op:
        batch_op.drop_column('booked_at')
        batch_op.drop_column('is_reserve')
        batch_op.drop_column('pair_no')
        batch_op.drop_column('on_date')

    with op.batch_alter_table('defense_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('starts_at', sa.TIME(), nullable=True))
        batch_op.add_column(sa.Column('on_date', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('slots_open', sa.BOOLEAN(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_defense_events_created_by_users'), type_='foreignkey')
        batch_op.drop_column('created_by')
        batch_op.drop_column('is_open')
        batch_op.drop_column('description')

    op.drop_table('topic_items')
    op.drop_table('topic_lists')
    op.drop_table('pinned_tasks')
    # ### end Alembic commands ###
